FROM node:20 AS build

# Disable SSL verification (⚠️ ONLY for dev!)
ENV NODE_TLS_REJECT_UNAUTHORIZED=0

WORKDIR /app
COPY package*.json ./
RUN npm config set strict-ssl false && npm install --omit=dev

COPY . ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html





