version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    volumes:
    - ./frontend:/app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_psw
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U enricotask"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
